export type Issue = {
  url: string; // "https://api.github.com/repos/ademilter/homepage/issues/33";
  repository_url: string; // "https://api.github.com/repos/ademilter/homepage";
  labels_url: string; // "https://api.github.com/repos/ademilter/homepage/issues/33/labels{/name}";
  comments_url: string; // "https://api.github.com/repos/ademilter/homepage/issues/33/comments";
  events_url: string; // "https://api.github.com/repos/ademilter/homepage/issues/33/events";
  html_url: string; // "https://github.com/ademilter/homepage/issues/33";
  id: number; // 1169640672;
  node_id: string; // "I_kwDOCLV3H85Ft0zg";
  number: number; // 33;
  title: string; // "Kod için hangi fontu kullanıyorsun?";
  state: "open";
  locked: false;
  assignee: null;
  assignees: [];
  milestone: null;
  comments: number; // 0;
  created_at: string; // "2022-03-15T12:57:46Z";
  updated_at: string; // "2022-03-15T12:57:46Z";
  closed_at: null;
  author_association: "OWNER";
  active_lock_reason: null;
  body: string; // "[JetBrains Mono](https://www.jetbrains.com/lp/mono/)";
  timeline_url: string; // "https://api.github.com/repos/ademilter/homepage/issues/33/timeline";
  performed_via_github_app: null;
  labels: {
    id: number; // 3930788377;
    node_id: string; // "LA_kwDOCLV3H87qSxIZ";
    url: string; // "https://api.github.com/repos/ademilter/homepage/labels/faq";
    name: string; // "faq";
    color: string; // "48488E";
    default: false;
    description: string; // "";
  };
  user: {
    login: string; // "ademilter";
    id: number; // 187922;
    node_id: string; // "MDQ6VXNlcjE4NzkyMg==";
    avatar_url: string; // "https://avatars.githubusercontent.com/u/187922?v=4";
    gravatar_id: string; // "";
    url: string; // "https://api.github.com/users/ademilter";
    html_url: string; // "https://github.com/ademilter";
    followers_url: string; // "https://api.github.com/users/ademilter/followers";
    following_url: string; // "https://api.github.com/users/ademilter/following{/other_user}";
    gists_url: string; // "https://api.github.com/users/ademilter/gists{/gist_id}";
    starred_url: string; // "https://api.github.com/users/ademilter/starred{/owner}{/repo}";
    subscriptions_url: string; // "https://api.github.com/users/ademilter/subscriptions";
    organizations_url: string; // "https://api.github.com/users/ademilter/orgs";
    repos_url: string; // "https://api.github.com/users/ademilter/repos";
    events_url: string; // "https://api.github.com/users/ademilter/events{/privacy}";
    received_events_url: string; // "https://api.github.com/users/ademilter/received_events";
    type: "User";
    site_admin: false;
  };
  reactions: {
    url: string; // "https://api.github.com/repos/ademilter/homepage/issues/33/reactions";
    total_count: number; // 0;
    "+1": number; // 0;
    "-1": number; // 0;
    laugh: number; // 0;
    hooray: number; // 0;
    confused: number; // 0;
    heart: number; // 0;
    rocket: number; // 0;
    eyes: number; // 0;
  };
};
