<template>
  <div class="VueToNuxtLogo">
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
       <picture>
        <source media="(min-width: 1200px)"
                :data-srcset="require('~/assets/site-cover-photo-3.jpg')">
        <source media="(min-width: 992px)"
                :data-srcset="require('~/assets/site-cover-photo-2.jpg')">
        <source media="(min-width: 768px)"
                :data-srcset="require('~/assets/site-cover-photo-1.jpg')">
        <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
            :data-src="require('~/assets/site-cover-photo-0.jpg')"
            class="img-fadein lazyload"
            alt="Adem ilter with daughter"
            data-expand="-30">
    </picture>
  </div>
</template>
