<template>
  <div class="VueToNuxtLogo">
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
       <picture>
        <source media="(min-width: 1200px)"
                data-srcset="http://a23.imgix.net/site-cover-photo.jpg?w=1.0&h=1300&fit=crop&crop=focalpoint&fp-x=0.5&fp-y=0.3&auto=format&q=60">
        <source media="(min-width: 992px)"
                data-srcset="http://a23.imgix.net/site-cover-photo.jpg?w=1200&h=900&fit=crop&crop=focalpoint&fp-x=0.5&fp-y=0.3&auto=format&q=60">
        <source media="(min-width: 768px)"
                data-srcset="http://a23.imgix.net/site-cover-photo.jpg?w=992&h=800&fit=crop&crop=focalpoint&fp-x=0.5&fp-y=0.3&auto=format&q=60">
        <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
            data-src="http://a23.imgix.net/site-cover-photo.jpg?w=768&auto=format&q=60"
            class="img-fadein lazyload"
            alt="Adem ilter with daughter"
            data-expand="-30">
    </picture>
  </div>
</template>
